server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/mch-back

spring:
  profiles:
    active: test
    group:
      test: h2
      dev: postgres
      prod: postgres
  application:
    name: mch
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: "test-secret"

cors:
  origin: "*"

#graphql:
#  servlet:
#    cors-enabled: true
#    cors:
#      allowed-origins:
#        - "*"
#      allowed-methods:
#        - "*"
#      allowed-headers:
#        - "*"
#      allowed-origin-patterns:
#        - "*"